Visão Lógica
UnBArqDsw2024-1/2024.1_G2_My_Music pull request #100
Opened 2024-08-11 01:46 UTC by IsraelThalles

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the CONTRIBUTING.md doc.
- [ ] I have added necessary documentation (if appropriate).
- [ ] Any dependent changes have been merged and published in downstream modules.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-08-11 21:49 UTC, yabamiah commented
Até então, o artefato possui seu objetivo muito bem cumprido já que foi demonstrado a visão do sistema em subsistemas e posteriormente em pacotes menores, demonstrando quais eram significativos. 

Através da minha revisão até então, observei que faltou a **metodologia** utilizada para realizar este artefato, contendo quais membros foram responsáveis, como, onde e quando a realizaram. Se possível, citar também os artefatos do próprio projeto que foram utilizados ao longo deste artefato, como o Diagrama de Atividades.

2024-08-11 23:14 UTC, IsraelThalles commented
> Através da minha revisão até então, observei que faltou a **metodologia** utilizada para realizar este artefato, contendo quais membros foram responsáveis, como, onde e quando a realizaram. Se possível, citar também os artefatos do próprio projeto que foram utilizados ao longo deste artefato, como o Diagrama de Atividades.

Quanto à metodologia, nós seguimos o *template* do DAS disponibilizado pela professora, onde não consta uma subseção de metodologia para cada visão. Mesmo assim, você acha necessário ter uma subseção de metodologia nesse documento?

2024-08-12 01:50 UTC, yabamiah commented
> > Através da minha revisão até então, observei que faltou a **metodologia** utilizada para realizar este artefato, contendo quais membros foram responsáveis, como, onde e quando a realizaram. Se possível, citar também os artefatos do próprio projeto que foram utilizados ao longo deste artefato, como o Diagrama de Atividades.
> 
> Quanto à metodologia, nós seguimos o _template_ do DAS disponibilizado pela professora, onde não consta uma subseção de metodologia para cada visão. Mesmo assim, você acha necessário ter uma subseção de metodologia nesse documento?

Acho que interessante para se manter no padrão dos nossos artefatos, e já que  na documentação das outras visões também foi seguido este padrão, fica melhor. Por via das dúvidas, amanhã será aula de dúvidas, podemos discutir sobre amanhã.

2024-08-12 20:17 UTC, IsraelThalles commented
Adicionei a metodologia, Vinícius.

2024-08-12 20:32 UTC, yabamiah requested changes
Com a metodologia ficou melhor ainda, com um breve comentário e citação dos artefatos aqui referênciadps. 

Última coisa, para manter este artefato no padrão tal qual os dos outros membros e dos artefatos já desenvolvidos até então, Poderia  colocar "## Introdução" depois de "# Visão Lógica", no mais, parabéns pelo artefato desenvolvido.

2024-08-12 21:05 UTC, IsraelThalles commented
> Com a metodologia ficou melhor ainda, com um breve comentário e citação dos artefatos aqui referênciadps.
> 
> Última coisa, para manter este artefato no padrão tal qual os dos outros membros e dos artefatos já desenvolvidos até então, Poderia colocar "## Introdução" depois de "# Visão Lógica", no mais, parabéns pelo artefato desenvolvido.

Feito.

2024-08-12 21:25 UTC, yabamiah commented
Tudo certinho, seu pr foi aceito.

2024-08-12 21:25 UTC, merged