Doc arq de software
UnBArqDsw2024-1/2024.1_G2_My_Music pull request #116
Opened 2024-08-14 22:14 UTC by HenriqueHida

Commit da criação do documento de arquitetura de software

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x ] I have read the CONTRIBUTING.md doc.
- [x ] I have added necessary documentation (if appropriate).
- [x ] Any dependent changes have been merged and published in downstream modules.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-08-15 01:41 UTC, LuisMiranda10 requested changes

2024-08-15 01:41 UTC, LuisMiranda10 commented on docs/ArquiteturaReutilizacao/arquiteturaDeSoftware.md
> +| `1.0`  | 12/08/2024 | Criação do documento e adição de todas as visões.                 | Henrique Hida           |        |
Aqui o histórico de versão deve seguir o padrão do projeto, logo, recomendo que coloque ao final do arquivo

2024-08-15 01:41 UTC, LuisMiranda10 commented on docs/ArquiteturaReutilizacao/arquiteturaDeSoftware.md
> +2. **Spotfy Web API.**. Disponível em: <https://developer.spotify.com/documentation/web-api>. Acesso em: 14 ago. 2024. [2]
Mesma coisa da revisão sobre o histórico de versão. Para seguir o padrão do projeto, recomendo colocar ao final do arquivo, entretanto, antes do histórico de versão (só olhar outros documentos feitos pelos integrantes)

2024-08-15 01:41 UTC, LuisMiranda10 commented on docs/ArquiteturaReutilizacao/arquiteturaDeSoftware.md
> +| **DER** - Diagrama Entidade-Relacionamento                  | Diagrama utilizado para modelar a estrutura lógica de um banco de dados, mostrando as entidades e os relacionamentos entre elas.
Nossa arquitetura não tem nada sobre MVC. Inclusive recomendo que coloque sobre nosso tipo de estilo arquitetural utilizado no projeto (cliente-servidor).  

Além do mais, DAS não significa "Diagrama de Arquitetura de Software", e sim "Documento de Arquitetura de Software".

Para que o documento não fique muito extenso, utilize como parâmetro esse documento do projeto do semestre anterior (https://unbarqdsw2023-1.github.io/2023.1_G3_ProjetoMercadoLivre/#/ArquiteturaReutilizacao/DocumentoArquiteturaSoftware). Inclusive coloque ele na bibliografia por favor.

2024-08-15 23:58 UTC, LuisMiranda10 requested changes

2024-08-15 23:58 UTC, LuisMiranda10 commented on docs/ArquiteturaReutilizacao/arquiteturaDeSoftware.md
> +Como modelo arquitetural, foi adotado o padrão cliente-servidor. Nesse modelo, a aplicação é dividida em dois componentes principais: o cliente, que é responsável pela interface do usuário e interaçã
Aqui você esqueceu de citar que estamos usando o firebase como nossa principal de dados e também para uma autenticação de usuário mais segura, utilizando métodos seguros, como por exemplo, o uso do algoritmo HASH dentro das senhas para maior segurança do usuário.  Faltou além disso, falar sobre a utilização da API do spotify, que é literalmente nosso ponto chave dentro do projeto.

2024-08-15 23:58 UTC, LuisMiranda10 commented on docs/ArquiteturaReutilizacao/arquiteturaDeSoftware.md
> +| **DAS** - Documento de Arquitetura de Software               | Representação visual que demonstra como os componentes de um sistema de software estão organizados e como interagem entre si.
A defiição do DAS ainda está como definição de um diagrama de arquitetura de software. Sugiro olhar o site abaixo para que coloque a definição correta (inclusive coloque ele na bibliografia caso seja necessário).

https://awari.com.br/documento-de-arquitetura-de-software-exemplo-e-estrutura-para-a-documentacao-adequada/

2024-08-16 00:09 UTC, HenriqueHida commented on docs/ArquiteturaReutilizacao/arquiteturaDeSoftware.md
> +Como modelo arquitetural, foi adotado o padrão cliente-servidor. Nesse modelo, a aplicação é dividida em dois componentes principais: o cliente, que é responsável pela interface do usuário e interaçã
É verdade, documentei essa parte no documento de visão e acabei esquecendo de adicionar ao tópico de representação arquitetural. Vou atualizar o documento

2024-08-16 00:50 UTC, HenriqueHida commented on docs/ArquiteturaReutilizacao/arquiteturaDeSoftware.md
> +| **DAS** - Documento de Arquitetura de Software               | Representação visual que demonstra como os componentes de um sistema de software estão organizados e como interagem entre si.
Resolvi os problemas apontados no commit [422f17d](https://github.com/UnBArqDsw2024-1/2024.1_G2_My_Music/pull/116/commits/422f17d5283fd4bf0a500c1d6c1f5806bdaa0321)

2024-08-16 03:00 UTC, LuisMiranda10 commented on docs/ArquiteturaReutilizacao/arquiteturaDeSoftware.md
> +| **DAS** - Documento de Arquitetura de Software               | Representação visual que demonstra como os componentes de um sistema de software estão organizados e como interagem entre si.
Certo, seu PR vai ser aceito.

2024-08-16 03:00 UTC, merged