Atualização diagrama de atividades
UnBArqDsw2024-1/2024.1_G2_My_Music pull request #38
Opened 2024-07-07 18:53 UTC by yabamiah

Atualização do diagrama de atividades

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the CONTRIBUTING.md doc.
- [ ] I have added necessary documentation (if appropriate).
- [ ] Any dependent changes have been merged and published in downstream modules.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-07-08 01:09 UTC, yabamiah commented
Eu atualizei o diagrama "Ouvir música".

2024-07-08 12:21 UTC, LuisMiranda10 requested changes
No diagrama ouvir música, foi repetido mais de uma vez o filtro de filtrar por artista

2024-07-08 12:26 UTC, yabamiah commented
Obrigado Luis pelo feedback!! O diagrama foi corrigido.

2024-07-08 12:28 UTC, LuisMiranda10 commented
Agora sim. Parabén pelo diagrama de atividades.

2024-07-08 12:30 UTC, merged

2024-07-09 16:45 UTC, IsraelThalles commented
A fim de registro:

Propus as seguintes alterações nos diagrama de "Cadastro" e de "Ouvir Música":

- Diagrama de Cadastro:
  - [ ] Remoção do nó de união, que vem antes do nó de decisão. Acredito que esse nó é desnecessário.
        <img src="https://github.com/UnBArqDsw2024-1/2024.1_G2_My_Music/assets/73364666/b61633e7-6cd8-4f86-9510-7aaacbc789f2" width="350">

- Diagrama de Ouvir Música:
  - [ ] Remoção do nó de união, que vem antes do nó de decisão. Acredito que esse nó é desnecessário.
        <img src="https://github.com/UnBArqDsw2024-1/2024.1_G2_My_Music/assets/73364666/33ac364d-b9f4-4ba2-8674-ea031747943a" width="350">
  - [ ] Fazer dos fluxos de adicionar filtro um fluxo alternativo/opcional.