37 diagrama de pacotes
UnBArqDsw2024-1/2024.1_G2_My_Music pull request #43
Opened 2024-07-09 01:39 UTC by Jvsoutomaior

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation Update (if none of the other choices apply)

## Checklist

- [X] I have read the CONTRIBUTING.md doc.
- [X] I have added necessary documentation (if appropriate).
- [X] Any dependent changes have been merged and published in downstream modules.

## Further comments

Closes #37

2024-07-09 03:43 UTC, IsraelThalles commented
### Lista de Requisitos de Revisão para o Diagrama de Pacotes
- Pacotes:
  - Os pacotes estão representados de maneira correta em de acordo com o UML? Sim.
  - Os pacotes  estão identificados de maneira concisa e descritiva? Sim.
- Conexões e Dependências:
  - As dependências entre os pacotes estão representadas corretamente? Sim.

Feedback: O diagrama está coerente com o material de referência apresentado ([https://www.lucidchart.com/pages/pt/diagrama-de-pacotes-uml](url)), considerando que é apenas um escopo inicial que ainda não possui todas as conexões. Não encontrei nenhum erro no diagrama, apenas um pequeno erro de escrita na metodologia do diagramaPacotes.md.

2024-07-09 14:35 UTC, IsraelThalles reviewed
### Lista de Requisitos de Revisão para o Diagrama de Pacotes
- Pacotes:
  - Os pacotes estão representados de maneira correta em de acordo com o UML? Sim.
  - Os pacotes estão identificados de maneira concisa e descritiva? Sim.
- Conexões e Dependências:
  - As dependências entre os pacotes estão representadas corretamente? Sim.
  - O diagrama possui todas as conexões entre os pacotes? Não (1)

Feedback:

1. Alguns pacotes não possuem conexões com nenhum outro pacote. Imagino que seja  para simplificar ou pelo fato de se tratar de um escopo inicial.

O diagrama está coerente com o material de referência apresentado ([https://www.lucidchart.com/pages/pt/diagrama-de-pacotes-uml](url)). Não encontrei nenhum erro no diagrama, apenas um pequeno erro de escrita na metodologia do diagramaPacotes.md (corrigido).

2024-07-09 20:35 UTC, analuizargds requested changes
- Retirar a fonte na introdução e deixar apenas em "Referência Bibliográfica"
- Nunca utilizar "abaixo" (ou acima ou a seguir, etc) para dizer onde está a figura. Em vez disso colocar "Na figura 1 é apresentado o diagrama em que representa a visão geral do diagrama de pacotes". Fazer a mesma coisa para a figura 2, pois figuras, tabelas, diagramas e etc devem sempre ser chamadas no texto.
- Padronizar a legenda da figura para "Figura 1: Diagrama de Pacotes. (Fonte: João, 2024). Fazer a mesma coisa para a figura 2. 
- Tirar o link do github das fontes das figuras.
- Revisar o texto em "Visão mais detalhada do FrontEnd e Backend" pois faltam alguns acentos e tem um "o" depois de "inclui o a camada de banco de dados"
- No diagrama nenhum pacote tem algum tipo de dependência entre si? Isso deve ser revisado com cuidado, acredito que pode ter que acrescentar algo.
- Após fazer as alterações colocar meu nome no histórico de versão (Ana Luíza Rodrigues https://github.com/analuizargds)

2024-07-10 00:07 UTC, Jvsoutomaior commented
> * Retirar a fonte na introdução e deixar apenas em "Referência Bibliográfica"

Acho bom deixar porque eu so copiei e colei o que tava escrito la

>     * No diagrama nenhum pacote tem algum tipo de dependência entre si? Isso deve ser revisado com cuidado, acredito que pode ter que acrescentar algo.

Como essa é apenas uma visão inicial eu acho que não precisa ter tanta preocupação quanto a isso

2024-07-10 02:01 UTC, merged