Fix diagrama componentes
UnBArqDsw2024-1/2024.1_G2_My_Music pull request #61
Opened 2024-07-24 02:32 UTC by LuisMiranda10

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I have read the CONTRIBUTING.md doc.
- [ ] I have added necessary documentation (if appropriate).
- [ ] Any dependent changes have been merged and published in downstream modules.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-07-24 17:55 UTC, yabamiah requested changes

2024-07-24 17:55 UTC, yabamiah commented on docs/Modelagem/diagramaComponentes.md
O artefato está muito melhor após as correções, única coisa que poderia deixá-lo melhor ainda é comentar com mais detalhe como essa atividade foi realizada em conjunto pelo dois membros, se houve alguma reunião, ou algo do tipo para que seja descrito a participação dos dois na confecção do diagrama.

2024-07-24 21:01 UTC, ominiIA requested changes
O documento está muito melhor que a entrega anterior. O diagrama contém:

portas 
conectores
dependências
conexões simples e complexas
estrutura interna do compartimento
classificador de estrutura

Tenho três apontamentos sobre o documento:

1 - Tem um dois links na referência bibliográfica iguais, ambos para a mesma página do lucidchart. Um deveria ser um link para os slides.

2 - Retirar numeração da bibliografia. Somente a referência bibliográfica tem numeração. Inclusive é melhor corrigir a numeração da referência bibliográfica para que o número fique no inicio e da mesma forma que foi utilizada no documento. Dessa forma:

¹ Slides - MODELAGEM UML ESTÁTICA. slide 46. Disponível em: https://www.lucidchart.com/pages/pt/diagrama-de-componentes-uml. Acesso em: 16 de Junho.

² Diagrama de Componentes UML. Disponível em: https://www.lucidchart.com/pages/pt/diagrama-de-componentes-uml. Acesso em: 12 de Abril.

³ MyMusic. 1.1.4 Protótipo, 2024. Disponível em: https://unbarqdsw2024-1.github.io/2024.1_G2_My_Music/Base/prototipo/. Acesso em: 7 de Julho.

3 - Acredito que para evidenciar o senso crítico no documento poderia incluir uma seção conclusão ou algo do tipo falando sobre o diagrama feito, por exemplo dizendo o motivo de ser implementado da forma que foi e que vai ser incrementado durante o desenvolvimento do projeto.

2024-07-24 21:04 UTC, analuizargds requested changes
O documento está muito melhor que a entrega anterior. O diagrama contém:

portas
conectores
dependências
conexões simples e complexas
estrutura interna do compartimento
classificador de estrutura

Tenho três apontamentos sobre o documento:

1 - Tem um dois links na referência bibliográfica iguais, ambos para a mesma página do lucidchart. Um deveria ser um link para os slides.

2 - Retirar numeração da bibliografia. Somente a referência bibliográfica tem numeração. Inclusive é melhor corrigir a numeração da referência bibliográfica para que o número fique no inicio e da mesma forma que foi utilizada no documento. Dessa forma:

¹ Slides - MODELAGEM UML ESTÁTICA. slide 46. Disponível em: https://www.lucidchart.com/pages/pt/diagrama-de-componentes-uml. Acesso em: 16 de Junho.

² Diagrama de Componentes UML. Disponível em: https://www.lucidchart.com/pages/pt/diagrama-de-componentes-uml. Acesso em: 12 de Abril.

³ MyMusic. 1.1.4 Protótipo, 2024. Disponível em: https://unbarqdsw2024-1.github.io/2024.1_G2_My_Music/Base/prototipo/. Acesso em: 7 de Julho.

3 - Acredito que para evidenciar o senso crítico no documento poderia incluir uma seção conclusão ou algo do tipo falando sobre o diagrama feito, por exemplo dizendo o motivo de ser implementado da forma que foi e que vai ser incrementado durante o desenvolvimento do projeto.

2024-07-24 21:20 UTC, LuisMiranda10 commented on docs/Modelagem/diagramaComponentes.md
Obrigado pelo feedback Vinicius, já realizei as mudanças depois verifique.

2024-07-24 21:21 UTC, LuisMiranda10 commented
Obrigado pelo feedback Ana, já realizei as mudanças, depois verifique.

2024-07-24 22:38 UTC, analuizargds commented
Revisado e aprovado!

2024-07-24 23:13 UTC, yabamiah approved these changes
Revisado e aprovado.

2024-07-25 00:55 UTC, analuizargds approved these changes

2024-07-25 02:13 UTC, merged