Primeira versão do Padrão de projeto Strategy
UnBArqDsw2024-1/2024.1_G2_My_Music pull request #64
Opened 2024-07-24 15:13 UTC by Jvsoutomaior

Co-authored-by: Carlos Godoy <cdgodoy17@gmail.com>
Co-authored-by: Carlos Eduardo <cmendesdemesquita@gmail.com>

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the CONTRIBUTING.md doc.
- [x] I have added necessary documentation (if appropriate).
- [x] Any dependent changes have been merged and published in downstream modules.

## Further comments

a nova pagina criada ainda não foi adicionada ao git pages

2024-07-24 20:06 UTC, yabamiah commented on docs/PadroesDeProjeto/GoFsExtras.md
> +## Introdução
A introdução está muito boa, porém, poderia ser apresentado brevemente a estrutura do padrão utilizado para ter uma base para acompanhar o resto do artefato.

2024-07-24 20:10 UTC, yabamiah commented on docs/PadroesDeProjeto/GoFsExtras.md
> +## Metodologia
Na metodologia, seria útil detalhar o contexto específico da aplicação MyMusic em que o padrão "Strategy" foi implementado. Dessa forma, ficaria mais fácil com de entender a modelagem e implementação com uma breve explicação sobre o motivo dessa implementação no contexto escolhido, proporcionando uma melhor compreensão da escolha do padrão e sua utilidade na aplicação.

2024-07-24 20:26 UTC, yabamiah commented on docs/PadroesDeProjeto/imagens/Strategy.png
1. De acordo com a estrutura do padrão Strategy, existe um elemento chamado `Context` que possui uma referência aos algoritmos implementados através de uma interface ou classe abstrata. Nesse contexto, o elemento "ListagemMusicas" seria o `Context`. No entanto, ao observar sua modelagem, "ListagemMusicas" não possui atributos ou métodos que referenciem os algoritmos que ele deveria conter.

2. Outro possível problema de semântica na modelagem abaixo é que não está claro quais elementos são classes abstratas, classes concretas ou interfaces. Isso dificulta a compreensão da estrutura e implementação do padrão Strategy no seu design.

2024-07-24 23:06 UTC, IsraelThalles requested changes
1. Adicione uma imagem com um caso geral de aplicação do Strategy.
2. Adicione legenda e fonte nas imagens e nos códigos.

2024-07-24 23:09 UTC, HenriqueHida reviewed
### Muito explicativo o documento. Mas aqui vão alguns pontos de correção que encontrei: 
1- A introdução menciona duas vezes que o padrão Strategy permite definir uma família de algoritmos e torná-los intercambiáveis. Está correto, mas acredito que a repetição pode ser evitada para tornar o texto mais conciso.

2- No parágrafo da Metodologia, tem um erro de digitação na palavra "traballhos".

3- O documento explica muito bem os benefícios do padrão Strategy, como facilitar a manutenção e escalabilidade do código, poderia ser interessante adicionar também algumas limitações, como o aumento na complexidade de código devido a criação de múltiplas classes.

2024-07-25 02:27 UTC, LuizPettengill reviewed
Algumas correções além as do Vinicius a serem observadas

2024-07-25 02:27 UTC, LuizPettengill commented on docs/PadroesDeProjeto/GoFsExtras.md
> +Para o aplicativo, foi decidido por usar o padrão "Strategy". O Strategy é um padrão de projeto comportamental que permite que você defina uma família de algoritmos, coloque-os em classes separadas,
"...mostrou-se o mais adequado para o uso e implementação Deste projeto, pois..." deixaria esse trecho da introdução mais adequada.

2024-07-25 02:27 UTC, LuizPettengill commented on docs/PadroesDeProjeto/GoFsExtras.md
> +Para a criação do strategy o grupo formou um trio (João Vítor, Carlos Godoy e Carlos Eduardo), que juntou em uma chamada de voz virtual para implementar o Padrão de Projeto comportamental Strategy, n
"...strategy formou-se um trio que se reuniu em chamada..."

Tá faltando acento no "nos", que pode ser alterado para 
"..., no qual foram utilizados como referência.."

2024-07-25 03:52 UTC, merged