Adicionando GoFs Criacoinais (+ ata da terceira reunião)
UnBArqDsw2024-1/2024.1_G2_My_Music pull request #65
Opened 2024-07-24 18:00 UTC by yabamiah

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the CONTRIBUTING.md doc.
- [ ] I have added necessary documentation (if appropriate).
- [ ] Any dependent changes have been merged and published in downstream modules.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-07-24 22:39 UTC, Jvsoutomaior commented
acredito que não seja uma boa pratica adicionar 2 coisas diferentes em uma mesma branch e pr

2024-07-25 00:04 UTC, analuizargds requested changes
Muito bom o documento pessoal. Vocês apresentaram um bom senso crítico sobre os padrões utilizados e mostraram domínio sobre o gof criacional. Foi possível verificar o motivo de terem escolhidos o Factory Method e o Singleton com apontamentos claros e a solução que esses padrões trazem.

Tenho alguns apontamentos sobre o documento:

1 - Não encontrei onde foi utilizada a referência ¹. Inclusive o link leva a uma página não encontrada

2 - Nos textos que antecedem os códigos é dito que anteriormente foi criado um pseudocódigo que pode ser visualizado no código X e posteriormente traduzido para Dart. Do modo como tá escrito dá a entender que vai haver o código de um pseudocódigo e do código em Dart.

3 - A legenda do diagrama do singleton aponta para a referência ¹. Deve ser corrigido para apontar para a referência específica de onde foi retirado a imagem. Algo como: 

```
Figura 3: Estrutura do padrão Singleton (Fonte: Refactoring Guru, 2014-2024)⁵

## Referência Bibliográfica

> ⁵ Singleton, Refactoring.Guru. Disponível em: https://refactoring.guru/pt-br/design-patterns/singleton. Acesso em: 15/07/2024.

 ```
4 - O histórico de versão que está sendo utilizado no projeto é 1.0 - 1.1 - 1.2 e assim por diante. Deve ser corrigido no documento para seguir o padrão

2024-07-25 00:40 UTC, Lucas-AV reviewed
Documento muito bem detalhado e bem escrito, ótimo trabalho.

Observações:
-> A motivação para a escolha dos GOFs Factory Method e Singleton está bem clara
-> A diagramação de cada um dos padrões está muito bem elaborada e é de fácil compreensão
-> O código precisava de algumas correções simples devido ao uso de alguns tipos de variáveis e objetos de forma incorreta como é o caso da ocorrência de "Date" ao invés de "DateTime" e "Objects" ao invés de "Object", a falta de ";" em algumas linhas e a inicialização da classe Perfil de forma errada dentro da classe abstrata CriadorPerfil, e a função criarPerfil passando por um override de forma errada sem instanciar a classe Perfil corretamente.

2024-07-25 01:50 UTC, rafaelxavierr commented
### Revisão do Pull Request: Padrões GoF Criacionais

#### Pontos Positivos:

- **Clareza e Estrutura**: A descrição dos padrões Factory Method e Singleton está bem estruturada, com explicações claras e detalhadas de cada componente envolvido.
- **Documentação Abrangente**: A cobertura detalhada dos conceitos, vantagens e desvantagens dos padrões Factory Method e Singleton.

#### Sugestões de Melhorias:

- **Melhoria de Exemplos**: Ampliar os exemplos de código para cobrir mais casos de uso, demonstrando a flexibilidade dos padrões.
- **Integração com Outros Padrões**: Exemplos de como Factory Method e Singleton podem ser integrados com outros padrões de design, como Abstract Factory ou Builder.
- **Discussão sobre Alternativas**: Exploração de alternativas aos padrões abordados, discutindo suas vantagens e desvantagens em comparação.

2024-07-25 01:51 UTC, LuisMiranda10 commented
> Muito bom o documento pessoal. Vocês apresentaram um bom senso crítico sobre os padrões utilizados e mostraram domínio sobre o gof criacional. Foi possível verificar o motivo de terem escolhidos o Factory Method e o Singleton com apontamentos claros e a solução que esses padrões trazem.
> 
> Tenho alguns apontamentos sobre o documento:
> 
> 1 - Não encontrei onde foi utilizada a referência ¹. Inclusive o link leva a uma página não encontrada
> 
> 2 - Nos textos que antecedem os códigos é dito que anteriormente foi criado um pseudocódigo que pode ser visualizado no código X e posteriormente traduzido para Dart. Do modo como tá escrito dá a entender que vai haver o código de um pseudocódigo e do código em Dart.
> 
> 3 - A legenda do diagrama do singleton aponta para a referência ¹. Deve ser corrigido para apontar para a referência específica de onde foi retirado a imagem. Algo como:
> 
> ```
> Figura 3: Estrutura do padrão Singleton (Fonte: Refactoring Guru, 2014-2024)⁵
> 
> ## Referência Bibliográfica
> 
> > ⁵ Singleton, Refactoring.Guru. Disponível em: https://refactoring.guru/pt-br/design-patterns/singleton. Acesso em: 15/07/2024.
> ```
> 
> 4 - O histórico de versão que está sendo utilizado no projeto é 1.0 - 1.1 - 1.2 e assim por diante. Deve ser corrigido no documento para seguir o padrão

Obrigado Ana, todas suas observações foram arrumadas.

2024-07-25 01:51 UTC, LuisMiranda10 commented
> Documento muito bem detalhado e bem escrito, ótimo trabalho.
> 
> Observações: -> A motivação para a escolha dos GOFs Factory Method e Singleton está bem clara -> A diagramação de cada um dos padrões está muito bem elaborada e é de fácil compreensão -> O código precisava de algumas correções simples devido ao uso de alguns tipos de variáveis e objetos de forma incorreta como é o caso da ocorrência de "Date" ao invés de "DateTime" e "Objects" ao invés de "Object", a falta de ";" em algumas linhas e a inicialização da classe Perfil de forma errada dentro da classe abstrata CriadorPerfil, e a função criarPerfil passando por um override de forma errada sem instanciar a classe Perfil corretamente.

Obrigado Lucas, todas suas observações foram arrumadas, obrigado pela leitura sobre o código.

2024-07-25 01:52 UTC, LuisMiranda10 commented
> * **s**: Exemplos de como Factory Method e Singleton podem ser integrados com outros padrões de design, como Abstract Factory ou Builder.
> * **Discussão sobre Alternativas**: Exploração de alternativas aos padrões abordados, discutindo suas vantagens e desvantagens em comparação.

Valeu Rafael, as mudanças foram analisadas e aproveitadas.

2024-07-25 03:18 UTC, IsraelThalles reviewed
Ainda não foi possível localizar onde foi usada a referência ¹, que a Ana mencionou.
Fora isso, o documento está bem estruturado, possui boa introdução e a modelagem aparenta estar correta.

2024-07-25 03:19 UTC, LuizPettengill commented
Por conta da qualidade inicial do documento e de ter sido o último revisor dos criacionais, não encontrei problemas nem o que adicionar a esse documento.
Mesmo sendo revisor, aprendi com facilidade o que são os métodos factory e singleton, e porque que eles serão tão bem utilizados no projeto My Music.

2024-07-25 03:25 UTC, LuisMiranda10 commented
> Ainda não foi possível localizar onde foi usada a referência ¹, que a Ana mencionou. Fora isso, o documento está bem estruturado, possui boa introdução e a modelagem aparenta estar correta.

Acabei de ver que na hora de commitar,  tinha dado erro, porém agora arrumei para que a referência seja encontrada na legenda.

2024-07-25 03:26 UTC, merged