Adicionando GOF Estrutural facade
UnBArqDsw2024-1/2024.1_G2_My_Music pull request #66
Opened 2024-07-24 20:04 UTC by HenriqueHida

Co-authored-by: [Lucas Vilela](https://github.com/Lucas-AV)
Co-authored-by: [Israel Thalles](https://github.com/IsraelThalles)
Co-authored-by: [Luiz Pettengill](https://github.com/LuizPettengill)

Adicionando o padrão de projeto estrutural Facade.

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the CONTRIBUTING.md doc.
- [x] I have added necessary documentation (if appropriate).
- [x] Any dependent changes have been merged and published in downstream modules.

2024-07-24 20:44 UTC, yabamiah commented on docs/PadroesDeProjeto/GoFsEstruturais.md
> +### Metodologia
1. Colocar mais referências de sites/artigos/videoaulas que foram utilizados  para auxiliar no desenvolvimento da modelagem e da implementação,
2. Adicionar um maior detalhamento do contexto no qual o padrão Facade foi utilizado no projeto MyMusic.

2024-07-24 21:22 UTC, Jvsoutomaior reviewed
Ja fiz um commit fazendo algumas corrreções de portugues e ja me adicionei e adicionei o Vinicios como revisores.

2024-07-24 21:29 UTC, analuizargds requested changes
Muito bom documento. Tenho alguns apontamentos:

1 - Os gofs estruturais vão ficar apenas nesse documento, não há necessidade de numeração (3.3.1 3.3.1.1) na minha opinião fica mais confuso então indico retirar essas numerações

2 - Na legenda da figura 2 está faltando o ano após os nomes dos autores

3 - O padrão do versionamento está incorreto. No projeto estamos utilizando 1.1 - 1.2 - 1.3 e assim por diante

4 - No documento não encontrei onde foi utilizada a referência (¹). Acredito que o local correto é na legenda da figura 1 que tem a referência (²), pois se refere a uma imagem do refactoring guru. Sendo assim é necessário corrigir essa parte e adicionar onde foi utilizada a referência (²)

2024-07-24 21:35 UTC, LimirioGuimaraes commented
# Lista de Revisão - Padrão Facade
   - [ ] O texto está claro e explica bem o propósito dos padrões estruturais.
   - [ ] A introdução ao padrão Facade é adequada e fornece um bom contexto.
   - [ ] A explicação cobre os principais componentes do padrão.
   - [ ] A utilização dafigura para ilustrar a estrutura do Facade é apropriada.
   - [ ] O exemplo em Dart é claro e compreensível.
   - [ ] O código dart é adequado ao contexto do projeto.
   - [ ] A metodologia de escolha do padrão é bem explicada.
   - [ ] As reuniões via Discord e o uso do Lucidchart são bem documentados.
   - [ ] As figuras estão corretamente referenciadas e legendadas.
   - [ ] Os links fornecidos nas referências estão ativos e acessíveis.
   - [ ] O histórico de versões está bem documentado e segue uma linha do tempo clara.
   - [ ] Todas as versões estão registradas corretamente e os autores estão listados corretamente.

## Feedback 
### Sugestões 
- Adicionar uma pequena seção sobre vantagens e desvantagens do uso do padrão Facade para fornecer uma visão mais completa.

2024-07-24 22:44 UTC, Jvsoutomaior commented
> 1 - Os gofs estruturais vão ficar apenas nesse documento, não há necessidade de numeração (3.3.1 3.3.1.1) na minha opinião fica mais confuso então indico retirar essas numerações

Acredito que fica mais facil ter um principal no documento e se forem adicionados extras seria bom estar em outro documento pois fica mais facil o controle de versionamento.

2024-07-25 00:00 UTC, LimirioGuimaraes reviewed
[Comentário da revisão](https://github.com/UnBArqDsw2024-1/2024.1_G2_My_Music/pull/66#issuecomment-2248941016)

2024-07-25 00:40 UTC, rafaelxavierr commented
Pontos Positivos:
Clareza e Estrutura: A descrição do padrão Facade está bem estruturada, com uma explicação clara e detalhada de cada componente envolvido.
Modelagem: A modelagem feita pelos intagrantes em cima do padrão parece bem pensada de acordo com o contexto do projeto.
Sugestões de Melhorias:
Metodologia: A seção de metodologia está bem elaborada, mas poderia incluir mais detalhes sobre os desafios encontrados e como foram superados.
Exemplos Reais: Talvez a inclusão de exemplos reais de como o padrão Facade é utilizado em outros projetos ou bibliotecas pode fornecer mais contexto e relevância.

2024-07-25 02:32 UTC, LuisMiranda10 commented on docs/PadroesDeProjeto/GoFsEstruturais.md
> +### Introdução
- Utilizar algum artigo para referenciar a introdução sobre a explicação do Facade
- Colocar uma conclusão para um melhor entendimento de onde foi utilizado o Facade, bem como suas respectivas motivações. Acredito ser algo que pode enriquecer mais o artefato.

2024-07-25 03:32 UTC, merged