56 gof comportamental command
UnBArqDsw2024-1/2024.1_G2_My_Music pull request #67
Opened 2024-07-24 22:56 UTC by analuizargds

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I have read the CONTRIBUTING.md doc.
- [X] I have added necessary documentation (if appropriate).
- [X] Any dependent changes have been merged and published in downstream modules.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-07-24 23:46 UTC, LimirioGuimaraes commented
### Lista de Verificação Command

- [ ] O objetivo dos padrões GoF comportamentais foi claramente explicado.
- [ ] A importância e o foco dos padrões GoF comportamentais foram bem contextualizados.
- [ ] A descrição da metodologia utilizada para criação do artefato foi bem elaborada.
- [ ] A descrição do padrão Command está clara e concisa.
- [ ] A estrutura do padrão Command está corretamente explicada e ilustrada na Figura 1.
- [ ] A descrição da modelagem do padrão Command foi detalhada adequadamente.
- [ ] O link para melhor avaliação do diagrama está acessível e funcional.
- [ ] Os exemplos de código foram incluídos corretamente e estão bem escritos.
- [ ] As fontes citadas são confiáveis e estão devidamente referenciadas.


### Feedbacks e sugestões
- A introdução do padrão localiza muito bem o leitor em relação a sua utilização no projeto.
- Colocar um título no artefato, deixa a documentação mais apresentável.

2024-07-24 23:53 UTC, LuisMiranda10 requested changes
Propus uma melhoria na Introdução do artefato.

2024-07-24 23:53 UTC, LuisMiranda10 commented on docs/PadroesDeProjeto/GoFsComportamentais.md
> +O Command é um padrão comportamental que transforma uma solicitação em um objeto, permitindo que o cliente parametrize outros objetos com diferentes solicitações, enfileire ou registre solicitações e
Acredito que aqui vocês podem citar algum artigo para que se tenha uma fonte e um maior enriquecimento na introdução

2024-07-25 00:15 UTC, Lucas-AV reviewed
O path das imagens dos diagramas no documento estava incorreto.

Outras observações:
-> A construção do texto do documento está muito bem elaborada.
-> Os exemplos de código estão bem escritos e são de fácil compreensão.
-> A descrição do Padrão Command está bem clara

2024-07-25 00:15 UTC, Lucas-AV commented on docs/PadroesDeProjeto/GoFsComportamentais.md
> +  <img src="../../Assets/EstruturaCommand.png" alt="Estrutura do Command" title="Command" />
O path no src dessa não está referenciado corretamente
```suggestion
  <img src="../Assets/EstruturaCommand.png" alt="Estrutura do Command" title="Command" />
```

2024-07-25 00:15 UTC, Lucas-AV commented on docs/PadroesDeProjeto/GoFsComportamentais.md
> +  <img src="../../Assets/ModelagemCommand.png" alt="Modelagem do Command" title="Modelagem do Command"/>
O path no src dessa não está referenciado corretamente
```suggestion
  <img src="../Assets/ModelagemCommand.png" alt="Modelagem do Command" title="Modelagem do Command"/>
```

2024-07-25 00:57 UTC, analuizargds commented on docs/PadroesDeProjeto/GoFsComportamentais.md
> +  <img src="../../Assets/ModelagemCommand.png" alt="Modelagem do Command" title="Modelagem do Command"/>
obrigado pela revisão. Fiz as correções

2024-07-25 00:57 UTC, analuizargds commented on docs/PadroesDeProjeto/GoFsComportamentais.md
> +O Command é um padrão comportamental que transforma uma solicitação em um objeto, permitindo que o cliente parametrize outros objetos com diferentes solicitações, enfileire ou registre solicitações e
Obrigado pela revisão. Fiz a correção

2024-07-25 02:42 UTC, LuizPettengill reviewed
Algumas propostas de melhorias

2024-07-25 02:42 UTC, LuizPettengill commented on docs/PadroesDeProjeto/GoFsComportamentais.md
> +    - Comandos Concretos implementam vários tipos de pedidos. Um comando concreto não deve realizar o trabalho por conta própria, mas passar a chamada para um dos objetos da lógica do negócio. Contud
Proposta de melhoria "...própria, deve passar a chamada..."

Na frase seguinte, quais seriam "essas classes"?

2024-07-25 02:42 UTC, LuizPettengill commented on docs/PadroesDeProjeto/GoFsComportamentais.md
> +    - Os parâmetros necessários para executar um método em um objeto destinatário podem ser declarados como campos no comando concreto. Você pode tornar os objetos comando imutáveis ao permitir que a
Proposta de melhoria ". Os objetos podem ser alterados para comandos imutáveis ao permitir...

2024-07-25 03:46 UTC, merged