Primeira versão da visão de dados
UnBArqDsw2024-1/2024.1_G2_My_Music pull request #84
Opened 2024-08-06 16:21 UTC by Jvsoutomaior

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the CONTRIBUTING.md doc.
- [x] I have added necessary documentation (if appropriate).
- [x] Any dependent changes have been merged and published in downstream modules.

## Further comments

Closes #78

2024-08-12 11:22 UTC, LuisMiranda10 requested changes

2024-08-12 11:22 UTC, LuisMiranda10 commented on docs/ArquiteturaReutilizacao/visaoDados.md
> +o Documento de Arquitetura de Software Visão de Dados é um documento opcional que abrange a visão de dados da aplicação. No caso da utilização de um Banco de Dados Relacional a visão de dados pode se
- A referência de algum artigo sobre a definição da visão de dados acabaria por enriquecer mais o trabalho. 
- Erros de ortografia: mER, generico.

2024-08-12 11:22 UTC, LuisMiranda10 commented on docs/ArquiteturaReutilizacao/visaoDados.md
> +Para o desenvolvimento do documento de visão de dados, primeiramente foi feito um estudo inicial de como deve ser esse documento, para o estudo foi utilizado video aulas e slides da professora Milene
- Melhorar a metodologia, colocando rastreabilidade nos artefatos que influenciaram para o desenvolvimento da VIsão de Dados. 
- Colocar a rastreabilidade no "Lucichart" que está no texto

2024-08-12 11:22 UTC, LuisMiranda10 commented on docs/ArquiteturaReutilizacao/visaoDados.md
> +
Colocar uma explicação dos componentes que estão no diagrama, você pode utilizar como parametro a visão de implementação ou implantação, na qual explica o diagrama

2024-08-12 13:34 UTC, LimirioGuimaraes commented
O documento está bem estruturado, no entanto deixo como sugestão: 
- Adicionar uma explicação textual sobre o fluxo apresentado no diagrama.

2024-08-13 23:53 UTC, CarlosEduardoMendesdeMesquita commented
Explicação e estruturação bem feitas, encontrei dois erros de digitação no entanto: último parágrafo da introdução, documento está escrito "dcoumento" e na metodologia Lucidchart está escrito "Lucichart", não impacta no entendimento, mas preferi citar.

2024-08-14 20:38 UTC, merged